### ISSUE TITLE
Error in gamedata file

### ISSUE THREAD

**Issue by MickaNoob** [Nolo001-Aha/File-Network#1]
Hi, I have this problem when i want to run the plugin. 

L 04/22/2023 - 11:05:24: [filenetwork.smx] [Gamedata] Could not find CBaseClient::GetNetChannel
L 04/22/2023 - 11:05:24: [SM] Exception reported: Gamedata failed, see error logs
L 04/22/2023 - 11:05:24: [SM] Blaming: filenetwork.smx
L 04/22/2023 - 11:05:24: [SM] Call stack trace:
L 04/22/2023 - 11:05:24: [SM]   [0] ThrowError
L 04/22/2023 - 11:05:24: [SM]   [1] Line 197, Z:\0_SOURCEMOD COMPILER\filenetwork.sp::OnPluginStart
L 04/22/2023 - 11:05:24: [SM] Unable to load plugin "filenetwork.smx": Error detected in plugin startup (see error logs)
L 04/22/2023 - 11:05:24: [SM] Unable to load plugin "rebanner.smx": Could not find required plugin "filenetwork"

I found the problem in the gamedata file: 

Before : 

```
            "CBaseClient::GetNetChannel"
            {
                "library"	"engine"
                "windows"	"\x8B\x81\x1C\x02\x00\x00\xC3"
		        "linux"      "55\x89\xE5\x8B\x45\x08\x5D\x8B\x80\x0C\x02\x00\x00\xC3"
                // Good Luck
            }
```

After:

```
            "CBaseClient::GetNetChannel"
            {
                "library"	"engine"
                "windows"	"\x8B\x81\x1C\x02\x00\x00\xC3"
		        "linux"      "\x55\x89\xE5\x8B\x45\x08\x5D\x8B\x80\x0C\x02\x00\x00\xC3"
                // Good Luck
            }
```

**Comment by Nolo001-Aha** [comment]
Hello.

Committed the fix, thank you.
Just checked the signature in IDA, it seems valid.
You may close the issue after you test.


If it doesn't work, then please post here.
